default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: esgg_development

test:
  <<: *default
  database: esgg_test

production:
  <<: *default
  database: <%= Rails.application.credentials.dig(:production, :postgres_db) %>
  username: <%= Rails.application.credentials.dig(:production, :postgres_username) %>
  password: <%= Rails.application.credentials.dig(:production, :postgres_password) %>
